[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    '@rari-capital/solmate/=lib/solmate/',
    'forge-std/=lib/forge-std/src/',
    'seaport-core/=lib/seaport-core/src/',
    'seaport-sol/=lib/seaport-sol/src/',
    'seaport-types/=lib/seaport-types/src/',
    'solady/=lib/solady/'
]

[fmt]
line_length = 80
tab_width = 4
bracket_spacing = true
